### ISSUE TITLE
connection_destroy_endpoint has memory leak

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/azure-uamqp-c#14]
This leak shows up when running the message_sender_sample.
It occurs because the realloc to 0 returns a NULL pointer but does not free the original block.

I have fixed with an if-else that checks for this case but is that the right fix?
Should amqpalloc_realloc be fixed?

**Comment by dcristoloveanu** [comment]
Hi @SparhawkSoftware ,

Thanks for reporting this!

I think the connection_destroy_endpoint fix is the right one in this case - to not do a realloc if (connection->endpoint_count - 1) is zero (basically shrinking the endpoints to zero size).

If you'd like to contribute this I'll merge it in.

Cheers,
/Dan

**Comment by SparhawkSoftware** [comment]
I found some more memory leaks in message_receiver_sample (does not clean up properly).

I am working on some OPC UA PubSub specific demos. I was thinking of forking to https://github.com/OPCFoundation unless you have an interest in adding such demos to the baseline.

**Comment by dcristoloveanu** [comment]
Hi @SparhawkSoftware,

I'd be definitely interested in taking the additional leaks out.
I guess if you have lots of samples they best fit in an OPC Foundation repo.
The 2 options I see are:
- Forking and adding samples in the fork like you mentioned
- Adding azure-uamqp-c as a submodule in the OPC Foundation repo where you host the samples.
I'd favor the submodule one since it avoids creating changes that are only for OPC-UA samples, thus giving you the option to pick up easily any fixes in uamqp. I might be biased since I did not have good experiences with maintaining forks of other projects, so I'd rather try to push the changes in those projects so that I do not have to maintain a fork.

If this makes things easier for you though we can park 1-2 OPC samples directly in the azure-uamqp-c repo, I have nothing against that.

Whenever you'd like to submit a PR to fix the memory leaks I'm more than happy to review and merge that in.

Cheers,
/Dan

**Comment by SparhawkSoftware** [comment]
Hi Dan,

The reason suggested a fork is I had to change the shared utils to get it compile with OpenSSL on windows. I am not sure you want those changes in the baseline. The main use cases for using OpenSSL on Windows are:

1) Someone is already using OpenSSL in their app and wants consistent behavior across Windows OSes (TLS 1.2 is supported by OpenSSL on Windows XP but not by SChannel).

2) Schannel requires that broker certs be signed by a CA in the trusted root certificate store. This precludes the use of third party stores (e.g. TPMs) to manage all certificates and trust relationships. 

If you are ok with incorporating these fixes into the baseline I could use a submodule.

Regards,

Randy

**Comment by dcristoloveanu** [comment]
Hi Randy,

If this is behind a cmake option, I'd actually love it!
Something like use_tlsio_openssl in cmake forcing OpenSSL usage on Windows would not hurt in anyway in my opinion.

This would also help you I believe with the fact that you don't have to maintain a fork.

Cheers,
/Dan

**Comment by SparhawkSoftware** [comment]
Submitted pull request: https://github.com/Azure/azure-uamqp-c/pull/16

**Comment by dcristoloveanu** [comment]
The fix for the leak has been merged into develop.
