### ISSUE TITLE
Please update setup docs to call out dependencies needed

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-uamqp-c#161]
We recently tried to build uamqp (not full IOT C SDK client) on Win10 Bash (Ubuntu) but had to work through many dependency issues.  

Could we update instructions to mention needing libssl-dev, libcurl-dev and libuuid-dev and anything else.  Presumably some step in setting up IOT Client (manual or automatic) or maybe just having an Ubuntu 16.04 VM handled right things vs Win10 Bash/Ubuntu combo?

**Comment by dcristoloveanu** [comment]
Thanks for filing this. The dependencies are actually due to C shared utility. Nevertheless a one liner for Ubuntu with the sudo apt-get-install args would make it slightly smoother. Even better would be a link to the readme of C shared so that we don't maintain in uAMQP the dependencies of the PAL for various targets.

Will look into this as time allows.
