### ISSUE TITLE
connection_on_bytes_received() returning error

### ISSUE THREAD

**Issue by jcwren** [Azure/azure-uamqp-c#175]
When I try to run the message_sender_sample, I get the following error:
```
jcw@debresc:~/azure/azure-uamqp-c/cmake$ samples/message_sender_sample/message_sender_sample
Current memory usage:18446744073709551615 (max:18446744073709551615)
Error: Time:Sun Aug 20 19:21:31 2017 File:/home/jcw/azure/azure-uamqp-c/src/connection.c Func:connection_on_bytes_received Line:665 Cannot process received bytes
^C
jcw@debresc:~/azure/azure-uamqp-c/cmake$
```
It does hang there, and the control-C is required to exit.

I believe I have the EH_* #defines set correctly. If I change the host name to something invalid, I get a connection ```getaddrinfo failure -5``` error (as expected). Unfortunately, changing any of the other three values don't cause a different error, so I can't prove that my key name, key, and event hub name are correct. They do, however, match the values in the Azure Event Hub portal, so I'm reasonably sure I've copied them correctly. I've obfuscated the EH strings below, but this is basically what I have:
```
#define EH_HOST "myeventhub.servicebus.windows.net"
#define EH_KEY_NAME "RootManageSharedAccessKey"
#define EH_KEY "ttorJEdzZsIs8mgGjz89AfjOzzVehMPsrUfUeYfuu2HepnA="
#define EH_NAME "eh1"
```

One thing I do notice is that the connection string in the Azure Event Hub portal uses "sb://" as the prefix, while the sample code uses "amqps://". I don't see any options specifically to specify AMPQ when creating the event hub.

**Comment by dcristoloveanu** [comment]
Thanks for reporting this, I accidentally broke the sample with my last commit by switching it to AMQP over raw TCP communication. Sorry about that.

PR #177 should address it, I am running it through the gated build as we speak.

Let me know if it fixes the issue for you and apologies.

Just FYI, trying to explain the amqps:// and sb:// :

amqps:// in the code is being used when creating the endpoint name that is used by service bus. Service bus has a certain convention for addressing the service bus namespaces. That is because the AMQP spec does not mandate how the addressing is done.
For example if you would look at which endpoint a C# AMQP client is targetting when talking to SB you would see the same amqps://

The sb:// is the prefix used in service bus connection strings and it is different than the internal prefix for the endpoints discussed above.

Cheers,
/Dan

**Comment by dcristoloveanu** [comment]
@jcwren The commit fixing the sample is now in master.
Let me know if it works now for you.

**Comment by jcwren** [comment]
That appeared to fix it. I still don't know enough about Azure to know how to go look at what it received from the sample (they seem to have made this insanely complex), but the message_sender_sample output indicates the messages were indeed pushed to the event hub.

Also, thank you for the explanation about the sb:// vs amqps://  prefixes. That was helpful.

**Comment by dcristoloveanu** [comment]
Glad it worked, closing the issue.

For the receiver part, you basically have to attach a receiver link to a certain endpoint and then SB will push the events to you.

You can find some example on how to do this in the EH client for C receiver.
I believe the most interesting part for you is how to construct the endpoint.

https://github.com/Azure/azure-event-hubs-c/blob/master/eventhub_client/src/eventhubreceiver_ll.c#L451 

Hope this helps.
/Dan
