### ISSUE TITLE
Missing timeout for messages

### ISSUE THREAD

**Issue by mario19911** [Azure/azure-uamqp-c#178]
Hey guys,

I think we figured out a problem when not all AMQP messages in the queue are acknowledged by a disposition frame.

Normally when the disposition frame arrives, the messages from the queue are freed. For the case that one disposition frame is missing (e.g. due to a broker error), these messages will never be freed and the memory remains allocated. 

I think there should be a timeout for every message in the queue, such that they will be freed after some time. Additionally, the callback for a received message needs to be called with a negative error code.

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Hi @mario19911 

Having a timeout for sending would be a nice feature. As a matter of fact all async APIs would deserve having a timeout.

The alternative here would be adding cancellation to the async APIs (like send/open). In that case the timeout can be measured by the user of the API as it wishes and the async operation can be cancelled cancelled at any point (for example when the timeout is detected).

Of course in both cases a separate error code would be indicated in the callback.

Let me think a bit how I would like the APIs to look like and I'll come back with them on this thread.

Thanks!
/Dan

**Comment by mario19911** [comment]
Hi @dcristoloveanu

thanks for your fast response. Just one more point I noticed regarding this problem: the timeout needs to be decremented in the context of the LINK_HANDLE with a tickercounter. Currently there is no cyclic function in the link that can be used for decrementing this timeout - I think the link needs to be extended with its own dowork method (but I got no idea if this idea fits in the design of the stack :))

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Hi @mario19911 

I just commited the addition of a timeout argument to link_transfer and to messagesender_send.
Please note that I renamed messagesender_send to messagesender_send_async and link_transfer to link_transfer_async (this is a minor change, but I wanted to give you a heads up).

Currently the messagesender_send_async just passes the timeout to link_transfer_async, so this can become innacurate if the message lurks in messagesender for a while until it gets passed to link_transfer_async (for example due to flow control).

To fix this there needs to be a mechanism of cancelling pending async operations, otherwise, callbacks could be triggered with contexts that have been already destroyed. To be precise, if messagesender is to detect a timeout, when it detects it, it must first cancel the link_transfer, otherwise a link_transfer delivery complete could be triggered with a context that was freed due to timeout.

I have another change in progress to start adding cancel-able async operations. Currently the WIP is on the async_operation branch. Will update you once it gets checked in.

Let me know if this works for you,

Cheers,
/Dan

**Comment by mario19911** [comment]
Hello @dcristoloveanu 

I will check that as soon as possible and let you know if there are any errors with that. Thank you for the fast enhancement!

Best regards,
Mario

**Comment by dcristoloveanu** [comment]
Closing as I assume this satisfies the needs for now. If not, let me know by simply opening a new issue.

Cheers,
/Dan
