### ISSUE TITLE
Multithreaded Usage

### ISSUE THREAD

**Issue by SparhawkSoftware** [Azure/azure-uamqp-c#20]
What recommendations are there for using this library from multiple threads?
e.g. one connection - one thread? one thread per process? one message_sender per thread?
Looking at the code it does not look thread safe.

**Comment by dcristoloveanu** [comment]
@SparhawkSoftware
Hi Randy,

There are no thread safety guarantees for the same object being used from multiple threads (for example connection/link, etc.).
Thus if there is at least one byte shared between 2 threads, there must be locking implemented in the caller (user code) to handle that.

However 2 different objects that do not share memory (for example 2 connections and all objects built on top of the connections - session, link, receiver, sender) can be used safely from different threads.

Extra caution should be taken for the following 2 cases:
- All memory tracing uses the same code and it is not meant to be thread safe
- the xio using openssl (tlsio_openssl.c) has extra static locks implemented to deal with the fact that openssl shares globals (per openssl documentation). Care should be taken to properly do the global init/deinit of openssl.

In IoTHubClient (that uses uAMQP) we have implemented a convenience layer that provides locking to the user, so that the user does not have to implement the locking code for one top level object. I guess this is really depending on the project which one is desirable (some low resource controllers will never care about locking and multithreading, while typical Linux distros and Windows will need that).

Hope this helps,
/Dan

**Comment by SparhawkSoftware** [comment]
I understand that the lack of synchronization is technically a feature for low end systems.
I just wanted to understand what I need to synchronize.

You answer appears to be:
1) Ensure platform_init() and platform_deinit() are called once;
2) Add one mutex for each connection which is used for all sessions/links created on that connection.

Is that correct?

**Comment by dcristoloveanu** [comment]
1) Yep.
2) I believe we're saying the same thing, just want to repeat so we're sure. If you have 2 message_sender objects on the same connection you would need to lock at the message_sender API, wrapping messagesender_open, messagesender_close, messagesender_send. If you operate directly with links (unlikely) then you would need to wrap the link APIs with a mutex.

Additional thing to take into account is that connection_dowork needs to be protected too, since that will trigger all the callbacks to the upper layers.

I can have a look at the locking once you have some sample code.

Hope this helps,
/Dan
