### ISSUE TITLE
supporting EventData_Properties when transmitting to Eventhub

### ISSUE THREAD

**Issue by ahmedawad1** [Azure/azure-uamqp-c#206]
Hi,

I am using "message_sender_sample" example to transmit to the Eventhub. However, in some other C- SDK which transmits to Eventhubs from Microsoft, exactly here-> "azure-event-hubs-c" SDK
[send.c](https://github.com/Azure/azure-event-hubs-c/blob/master/eventhub_client/samples/send/send.c)

Some features such as `EventData_Properties(eventDataHandle);`  at line116 in the send.c code in link above are implemented. 

I can not find such implementation in this SDK "azure-uamqp-c", does it support transmitting EventData_Properties as well and if yes can you please show me where is the function which does so ? 

I searched alot in the github repository but can not find such implementation.

Thanks in advance,

**Comment by dcristoloveanu** [comment]
@ahmedawad1 Sorry for the delay in the reply.

uamqp does not implement the EH properties, since it is a general purpose AMQP library.
However EH properties are encoded as application properties and that means basically building an AMQP map with amqpvalue_create_map and adding the values to the map. Then this map can be passed as application properties to the message.

In the EH SDK for C repo there is some sample code that does just that, takes the EventData properties and marshalls them into AMQP application properties.
Here is the link https://github.com/Azure/azure-event-hubs-c/blob/b36bea9d685daf2f05109165fa479d77ac29df8d/eventhub_client/src/eventhubclient_ll.c#L1472 

Hope this helps,.
/Dan

**Comment by ahmedawad1** [comment]
Thanks very much Dan! I used it actually and when I activated the message-sender trace, it pasted on the screen the application properties.
