### ISSUE TITLE
uamqp crashes on multiplexing tests

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-uamqp-c#217]
REPRO STEPS:
git clone https://github.com/Azure/azure-iot-sdk-c/ on commit id#8883cde388812fbf4fa9cc6f5ee9a020fdb4423a
build iothub_client\tests\iothubclient_amqp_modules_device_method_e2e (this is on Windows 10 64bit but seems not device specific)
run the exe 
get a crash 

The repo this is running against is for bringing up modules e2e.  Modules from uamqp perspective are just different URI's passed around and shouldn't impact anything.

It's possible the IoT C SDK is doing something wrong here, at 1st blush this is pretty deep in uAMQP so opening issue here.  Note that when I was single-stepping some I did not get crash repro.

What's happening is the 1st test run of iothubclient_amqp_modules_device_method_e2e, IotHub_AMQP_Method_Call_With_String_sas_multiplexed_single_device, fails because of a test bug on my side.  
We then continue on to executing IotHub_AMQP_Method_Call_With_String_sas_multiplexed, but because we hit an ASSERT in 1st test its not cleaned up properly and still active as 2nd test runs.

Eventually `on_link_state_changed` is called on the link from 1st test with `LINK_STATE_DETACHED`.  
The problem here is that we destroy the message_sender memory in the `set_message_sender_state` call, but after this call we call `indicate_all_messages_as_error` which assumes `message_sender` is still valid.  With LogInfo() I've determined that the `message_sender` is the one allocated from initial failed test.

```c
static void on_link_state_changed(void* context, LINK_STATE new_link_state, LINK_STATE previous_link_state)

    case LINK_STATE_DETACHED:
        if ((message_sender->message_sender_state == MESSAGE_SENDER_STATE_OPEN) ||
            (message_sender->message_sender_state == MESSAGE_SENDER_STATE_CLOSING))
        {
        	LogInfo("Detatched: %p", message_sender);
            /* User initiated transition, we should be good */
            set_message_sender_state(message_sender, MESSAGE_SENDER_STATE_IDLE);  // <=== messagesender_destroy called by this, see callstack below
            indicate_all_messages_as_error(message_sender); // <=== assumes message_sender still valid but it's been deleted.
        }
```

 
This is callstack where we do the destroy that causes later problems
```
 # Call Site
00 iothubclient_amqp_modules_device_method_e2e_exe!messagesender_destroy
01 iothubclient_amqp_modules_device_method_e2e_exe!iothubtransportamqp_methods_unsubscribe
02 iothubclient_amqp_modules_device_method_e2e_exe!on_methods_unsubscribed
03 iothubclient_amqp_modules_device_method_e2e_exe!call_methods_unsubscribed_if_needed
04 iothubclient_amqp_modules_device_method_e2e_exe!on_message_sender_state_changed
05 iothubclient_amqp_modules_device_method_e2e_exe!set_message_sender_state
06 iothubclient_amqp_modules_device_method_e2e_exe!on_link_state_changed
07 iothubclient_amqp_modules_device_method_e2e_exe!set_link_state
08 iothubclient_amqp_modules_device_method_e2e_exe!link_frame_received
09 iothubclient_amqp_modules_device_method_e2e_exe!on_frame_received
0a iothubclient_amqp_modules_device_method_e2e_exe!on_amqp_frame_received
0b iothubclient_amqp_modules_device_method_e2e_exe!frame_received
0c iothubclient_amqp_modules_device_method_e2e_exe!frame_codec_receive_bytes
0d iothubclient_amqp_modules_device_method_e2e_exe!connection_byte_received
0e iothubclient_amqp_modules_device_method_e2e_exe!connection_on_bytes_received
0f iothubclient_amqp_modules_device_method_e2e_exe!on_underlying_io_bytes_received
10 iothubclient_amqp_modules_device_method_e2e_exe!on_underlying_io_bytes_received
11 iothubclient_amqp_modules_device_method_e2e_exe!socketio_dowork
12 iothubclient_amqp_modules_device_method_e2e_exe!xio_dowork
13 iothubclient_amqp_modules_device_method_e2e_exe!tlsio_schannel_dowork
14 iothubclient_amqp_modules_device_method_e2e_exe!xio_dowork
15 iothubclient_amqp_modules_device_method_e2e_exe!saslclientio_dowork
16 iothubclient_amqp_modules_device_method_e2e_exe!xio_dowork
17 iothubclient_amqp_modules_device_method_e2e_exe!connection_dowork
18 iothubclient_amqp_modules_device_method_e2e_exe!amqp_connection_do_work
19 iothubclient_amqp_modules_device_method_e2e_exe!IoTHubTransport_AMQP_Common_DoWork
1a iothubclient_amqp_modules_device_method_e2e_exe!IoTHubTransportAMQP_DoWork
1b iothubclient_amqp_modules_device_method_e2e_exe!transport_worker_thread
1c KERNEL32!BaseThreadInitThunk
1d ntdll!RtlUserThreadStart
```

**Comment by dcristoloveanu** [comment]
Thanks for reporting this, you are right it seems the indicate_all_messages_as_error should come before the set_message_sender_state. Let me attempt at a fix.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
Here are my notes:
- uAMQP indicates a state change for the sender to the user by calling on_message_sender_state_changed.
- The user is the C2D methods in AMQP transport. The C2D module decides to report this up to the transport as an unsubscribed event.
- The transport decides to do an unsubscribe (to cleanup things)
- Unfortunately unsubscribe goes and kills the message sender object (still in the context of the callback from message_sender). This is a no-no and this is the root of the issue.

A workaround would be to indicate all messages with error before setting the state but I think this is not really the fix, since it could very well be that we still end up executing something on this message_sender object after the set_message_sender_state comes back - after it killed the message_sender.

So a good fix is a bit tricky and might mean we have to do some more work:
Normally unsubscribe should not have to delete objects in the C2D methods transport of IoTHub SDK. It needs to because there is no way to pass a link at open in message_sender. Basically I think the message_sender_open should be modified to get the link handle (and this link handle should be forgotten in _close and the message_sender brought to a clean state in close). In this way the same message_sender object can be used throughout the lifetime of the C2D AMQP transport methods module.

**Comment by dcristoloveanu** [comment]
@jspaith Could you please verify if this issue is still present on the latest master?
There were a couple of fixes regarding link and session management and I suspect this could have been because of those (already fixed) issues.

Thanks!
/Dan

**Comment by dcristoloveanu** [comment]
Closing as old, please reopen if a similar crash is encountered again.

Thanks!
/Dan
