### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-uamqp-c#226]
Hello,

We are seeing the following errors when trying to run on Ubuntu 16.04.2 LTS with OpenSSL:
uamqp.c_uamqp : b'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed'
uamqp.c_uamqp : b'Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR'
uamqp.c_uamqp : b'AMQP management instance not open' (b'./src/vendor/azure-uamqp-c/src/amqp_management.c':b'amqp_management_close':997)
uamqp.c_uamqp : CBS completed opening with status: 1

Given it's location, this may be an issue with the Shared Utilities lib, however I though I'd arise it here first to see if anyone has seen this before or has any thoughts on what I could check in order to debug it.
The test in question (including credentials, endpoint etc) works on Windows (using schannel).

Thanks!

FYI @digimaun

**Comment by dcristoloveanu** [comment]
Hi @annatisch 

The issue you are encountering is I believe because the openssl adapter in C shared (tlsio_openssl) is not calling SSL_CTX_set_default_verify_paths.

Since many distros used in IoT environments do not contain uptodate certs anyway, the certs were typically passed explictly to the openssl instance rather than relying on the OS to have them.

I do see how in your case you would want to use the OS one if they exist.
I think the issue should be fixed in tlsio_openssl in C shared.

I will close the issue here and add the information to the one in C shared.
Also adding a repro there would probably help.

Thanks,
/Dan

**Comment by annatisch** [comment]
Thanks @dcristoloveanu!
I believe it must have been an invalid cmake config on my part. Not quite sure how but I've just cleaned out my bindings and rebuilt everything and it seems to be working now :)
