### ISSUE TITLE
CPU usage in IO operations

### ISSUE THREAD

**Issue by nicolodanzi** [Azure/azure-uamqp-c#23]
I noticed that in the samples all IO operations (connection, send a message, authenticate, create message sender) are performed by a "connection_dowork" function that schedules the internal operations. This function is always enclosed in an endless while loop that breaks because of the flags set by the callbacks.

The drawback of this pattern is that each operation performed by the "connection_dowork" function within the while loop stresses the CPU (100% usage). In fact no asynchronous operation is performed by the "connection_dowork" function to prevent from stressing the CPU.

Is this the way this library is meant to be used? Are there any alternatives to use asynchronous operations in order to avoid stressing the CPU in the endless while loop?

Thanks in advance
Nicolò

**Comment by dcristoloveanu** [comment]
Hi @nicolodanzi,

Sorry for the delay, vacation times take the toll ...
The only model available now is indeed that the user schedules when the library performs the needed work (which is typically a loop with some yield (sleep)). This works quite OK for various embedded environments since it requires (almost) no porting.

The alternative of using a select like mechanism came into discussion several times and it would be nice to have such a mechanism, but I never got to look at it unfortunately due to other priorities ...

Not sure if this helps in any way.

To answers the 2 questions:

Is this the way this library is meant to be used?
Yes

Are there any alternatives to use asynchronous operations in order to avoid stressing the CPU in the endless while loop?
Not right now.

Cheers,
/Dan

**Comment by alex-picolini** [comment]
Hi, any update?
