### ISSUE TITLE
removing absolute paths from the compiled libs (libuamqp.a & libaziotsharedutil.a)

### ISSUE THREAD

**Issue by ahmedawad1** [Azure/azure-uamqp-c#237]
Hi Everyone,

it is pretty easy to compile these libs but I have a little issue. When I link my code with the static libs (libuamqp.a & libaziotsharedutil.a) and if an error happens, then I get the absolute path where I originally compiled them. for example:

`Error ...........:/home/my_host_name/azure-uamqp-sources/azure-uamqp-c/src/sasclient.c`

I want when such an error appears on the console, the absolute path of my host does not show up. 

Please how can I compile the libraries such that my host name doesn't come up on the screen when the final binary runs which was linked with the static libs (libuamqp.a & libaziotsharedutil.a) ?

Thanks in advance

**Comment by dcristoloveanu** [comment]
Hi @ahmedawad1 

I assume you are referring to the LogErrors spewed by uamqp and C shared util. The filepaths there are due to the fact that LogError [spews __FILE__ as part of the entire log line](https://github.com/Azure/azure-c-shared-utility/blob/adcdd2306fc68b537d1c090068a235e5f85437d4/inc/azure_c_shared_utility/xlogging.h#L88).

This information was there so it can allow easier tracing of what happens in case of errors.

The full path logging happens because __FILE__ is expanded to whatever is passed to gcc as file path for the compiled .c file.
cmake passes absolute paths. There was once a CMAKE_USE_RELATIVE_PATHS that would have been perfect for  you (https://stackoverflow.com/questions/45856955/how-to-tell-cmake-to-use-relative-paths).
It still exists in cmake 3.0.2. You can use it with that cmake version if you are OK with downgrading to it.

So in summary, I would see the following solutions:
i) Make sure you use cmake 3.0.2 and pass CMAKE_USE_RELATIVE_PATHS when generating your makefiles with cmake. This will only print the relative paths and thus would not "leak" any of your specific paths.
ii) Add a compile switch in C shared utility.
a) One option is to add something along the lines for DO_NOT_LOG_FILENAMES as a cmake option in C shared to that no path appears if you are not interested in it. If you would PR it it could probably picked up pretty fast, otherwise I would think of this as a lower priority item compared to the other open issues in C shared. I would not really go this route TBH.
b) Another option of changing LogError would be to only put the relative path in the log line instead of the entire __FILE__. A solution on how to change it is here: https://stackoverflow.com/questions/8487986/file-macro-shows-full-path.
iii) Build in a path that does not reveal much information. This is the easiest, no code change, but it might be inadequate for you.

If you are not tied to a specific cmake version the preferred thing to do is probably use 3.0.2, as it is the least effort on all sides.

Hope this helps,
/Dan

**Comment by ahmedawad1** [comment]
Thank you very much Dan for the informative answer!
