### ISSUE TITLE
SASL handshake failed

### ISSUE THREAD

**Issue by HyP3r-** [Azure/azure-uamqp-c#244]
Hello, we are using **azure-uamqp-c** as part of the Python Package **azure-iothub-service-client** (which is part of the **azure-iot-sdk-python** which is part of the **azure-iot-sdk-c**). 

Now I was trying to change the Share Access Polices from **iothubowner** to **service** in my code to imporve the security. But with the **service** Share Access Polices I get following error:

`Error: Time:Wed Jun 20 15:14:29 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\uamqp\src\saslclientio.c Func:_on_sasl_frame_received_callback Line:901 SASL handshake failed with code 02`

For troubleshooting I granted the **service** Share Access Polices the same IoT Hub permissions as the **iothubowner** but I still get this error. Why?

![2018-06-20_15-30-47](https://user-images.githubusercontent.com/8094242/41661388-f037da78-749e-11e8-8001-b4b2d831356f.png)
![2018-06-20_15-30-53](https://user-images.githubusercontent.com/8094242/41661389-f054fdba-749e-11e8-9231-b5ffeb4e603a.png)

**Comment by dcristoloveanu** [comment]
Hi @HyP3r- 

Thanks for filing the issue. Per the AMQP standard a response of 2 (sys) in the SASL handshake indicates a server error when processing the request (Connection authentication failed due to a system error.).

This error gets indicated to the user of uamqp (azure-iothub-service-client) so unfortunately I think the issue lies either in that layer or some other error happened on the server side.

I am adding @zolvarga here who owns the azure-iot-sdk-python and has all the knowledge of how service client sets up the SASL handshake and I would encourage opening an issue in that repo if not open already. @zolvarga, could you investigate this one further?

Thanks,
/Dan

**Comment by zolvarga** [comment]
@HyP3r- 

I will move (close here and copy paste to there) this issue to the azure-iot-sdk-python repo and follow up on that there.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@HyP3r- 

This is the new issue t ofollow up:
https://github.com/Azure/azure-iot-sdk-python/issues/149

Best Regards,
Zoltan
