### ISSUE TITLE
CMake fails to find "/configs/azure_iot_build_rules.cmake" when use_installed_dependencies=ON

### ISSUE THREAD

**Issue by seanyen-msft** [Azure/azure-uamqp-c#262]
When you do something like:
```
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -Duse_installed_dependencies=ON .
```

You will get:
```
CMake Error at CMakeLists.txt:52 (include):
  include could not find load file:

    /configs/azure_iot_build_rules.cmake
```

Probably CMakeLists.txt:52 needs a fix-up like:
`include(deps/azure-c-shared-utility/configs/azure_iot_build_rules.cmake)`

**Comment by dcristoloveanu** [comment]
Hi @seanyen-msft 

I am not very much into the use_installed_dependencies business :-). I understand that there are clearly cases where that is needed though, so assuming the above works for you, if you PR it, I will pull it in.

HTH,
/Dan

**Comment by dcristoloveanu** [comment]
Hi @seanyen-msft ,
I looked at the PR and I changed it slightly to use either deps directly or the SHARED_UTIL_FOLDER depending on whether building with installed dependencies or not.

The reason is that normally uamqp should not necessarily require the repos that submodule uamqp to pull all the dependent repos.
One would then ask why not pull them. It turns out that pulling all the submodules all the time for all the repos adds significantly to the clone time (and other issues come it too).

That is why the direction is to have the repos only require submodule update --init, without the recursive.

To handle that there are cases where the deps/azure-c-shared-utility would not be there, but in some other path.

And as I want to also make it work for you and also allow this case of the deps not necessarily being in deps/, I changed the PR as you can see it in master.

Let me know if this work for you or not.

And sorry for the delay!

Cheers,
/Dan
